name: release
on:
  push:
    tags:
      - "v*"
jobs:
  build-linux-and-darwin:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Install upx
        run: apt-get install -y upx-ucl
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2.5.0
        with:
          version: latest
          args: release --clean
        env:
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
          # GitHub sets this automatically
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_ALEX_HOMEBREW_METALSOFT }}
  build-windows:
    runs-on: windows-latest
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Build
        run: go build . && upx *.exe
      #- name: Sign
      #  uses: "InertiaSystems/code-sign-action@v1.1.0"
      #  with:
      #    certificate: "${{ secrets.CSR_CERTIFICATE }}"
      #    password: "${{secrets.CERTPASS}}"
      #    certificatesha1: "${{secrets.CERTHASH}}"
      #    certificatename: "${{ secrets.CERTNAME }}"
      #    timestampUrl: "http://timestamp.sectigo.com"
      #    folder: "."
      #    recursive: false
      - name: Create Archive
        uses: TheDoctor0/zip-release@0.6.1
        with:
          type: "zip"
          path: "*.exe"
          filename: "metalcloud-cli_${{github.ref_name}}_windows_amd64.zip"
          exclusions: "*.git* /*node_modules/* .editorconfig"
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "metalcloud-cli_${{github.ref_name}}_windows_amd64.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
